(package "undersea-theme"
         "0.3"
         "Theme styled after undersea imagery")

(website-url "https://github.com/jcs-elpa/undersea-theme")
(keywords "theme" "sea")

(package-file "undersea-theme.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
